function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 16-Jul-2016 17:43:18

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.95;  % Stopband Frequency
    Fpass = 1;     % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 1;     % Passband Ripple (dB)
    Fs    = 500;   % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'FilterStructure', 'df1sos', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

