function y = doFilter(x)
    Hd = designfilt('highpassiir',...
        'FilterOrder',10, ...
        'HalfPowerFrequency',1, ...
        'DesignMethod','butter', ...
        'SampleRate',500);
    y = filter(Hd,x);

