function [RR1,DET1,LMAX1,ENT1,LAM1,TT1,RR2,DET2,LMAX2,ENT2,LAM2,TT2,RR3,DET3,LMAX3,ENT3,LAM3,TT3,RR4,DET4,LMAX4,ENT4,LAM4,TT4,IiSQI,IbSQI,IpSQI,IsSQI,IkSQI,IfSQI,IIiSQI,IIbSQI,IIpSQI,IIsSQI,IIkSQI,IIfSQI,IIIiSQI,IIIbSQI,IIIpSQI,IIIsSQI,IIIkSQI,IIIfSQI,AVRiSQI,AVRbSQI,AVRpSQI,AVRsSQI,AVRkSQI,AVRfSQI,AVLiSQI,AVLbSQI,AVLpSQI,AVLsSQI,AVLkSQI,AVLfSQI,AVFiSQI,AVFbSQI,AVFpSQI,AVFsSQI,AVFkSQI,AVFfSQI,V1iSQI,V1bSQI,V1pSQI,V1sSQI,V1kSQI,V1fSQI,V2iSQI,V2bSQI,V2pSQI,V2sSQI,V2kSQI,V2fSQI,V3iSQI,V3bSQI,V3pSQI,V3sSQI,V3kSQI,V3fSQI,V4iSQI,V4bSQI,V4pSQI,V4sSQI,V4kSQI,V4fSQI,V5iSQI,V5bSQI,V5pSQI,V5sSQI,V5kSQI,V5fSQI,V6iSQI,V6bSQI,V6pSQI,V6sSQI,V6kSQI,V6fSQI,label]=bootstrapingData(RR1,DET1,LMAX1,ENT1,LAM1,TT1,RR2,DET2,LMAX2,ENT2,LAM2,TT2,RR3,DET3,LMAX3,ENT3,LAM3,TT3,RR4,DET4,LMAX4,ENT4,LAM4,TT4,IiSQI,IbSQI,IpSQI,IsSQI,IkSQI,IfSQI,IIiSQI,IIbSQI,IIpSQI,IIsSQI,IIkSQI,IIfSQI,IIIiSQI,IIIbSQI,IIIpSQI,IIIsSQI,IIIkSQI,IIIfSQI,AVRiSQI,AVRbSQI,AVRpSQI,AVRsSQI,AVRkSQI,AVRfSQI,AVLiSQI,AVLbSQI,AVLpSQI,AVLsSQI,AVLkSQI,AVLfSQI,AVFiSQI,AVFbSQI,AVFpSQI,AVFsSQI,AVFkSQI,AVFfSQI,V1iSQI,V1bSQI,V1pSQI,V1sSQI,V1kSQI,V1fSQI,V2iSQI,V2bSQI,V2pSQI,V2sSQI,V2kSQI,V2fSQI,V3iSQI,V3bSQI,V3pSQI,V3sSQI,V3kSQI,V3fSQI,V4iSQI,V4bSQI,V4pSQI,V4sSQI,V4kSQI,V4fSQI,V5iSQI,V5bSQI,V5pSQI,V5sSQI,V5kSQI,V5fSQI,V6iSQI,V6bSQI,V6pSQI,V6sSQI,V6kSQI,V6fSQI,label)
    acceptableCount=sum(label==1);    
    unacceptableCount=sum(label==-1);
    %% resample
    %RQA1
    RR1=resampleingData(RR1,acceptableCount,unacceptableCount,label);
    DET1=resampleingData(DET1,acceptableCount,unacceptableCount,label);
    LMAX1=resampleingData(LMAX1,acceptableCount,unacceptableCount,label);
    ENT1=resampleingData(ENT1,acceptableCount,unacceptableCount,label);
    LAM1=resampleingData(LAM1,acceptableCount,unacceptableCount,label);
    TT1=resampleingData(TT1,acceptableCount,unacceptableCount,label);
    %RQA2
    RR2=resampleingData(RR2,acceptableCount,unacceptableCount,label);
    DET2=resampleingData(DET2,acceptableCount,unacceptableCount,label);
    LMAX2=resampleingData(LMAX2,acceptableCount,unacceptableCount,label);
    ENT2=resampleingData(ENT2,acceptableCount,unacceptableCount,label);
    LAM2=resampleingData(LAM2,acceptableCount,unacceptableCount,label);
    TT2=resampleingData(TT2,acceptableCount,unacceptableCount,label);
    %RQA3
    RR3=resampleingData(RR3,acceptableCount,unacceptableCount,label);
    DET3=resampleingData(DET3,acceptableCount,unacceptableCount,label);
    LMAX3=resampleingData(LMAX3,acceptableCount,unacceptableCount,label);
    ENT3=resampleingData(ENT3,acceptableCount,unacceptableCount,label);
    LAM3=resampleingData(LAM3,acceptableCount,unacceptableCount,label);
    TT3=resampleingData(TT3,acceptableCount,unacceptableCount,label);
    %RQA4
    RR4=resampleingData(RR4,acceptableCount,unacceptableCount,label);
    DET4=resampleingData(DET4,acceptableCount,unacceptableCount,label);
    LMAX4=resampleingData(LMAX4,acceptableCount,unacceptableCount,label);
    ENT4=resampleingData(ENT4,acceptableCount,unacceptableCount,label);
    LAM4=resampleingData(LAM4,acceptableCount,unacceptableCount,label);
    TT4=resampleingData(TT4,acceptableCount,unacceptableCount,label);
    % I II III
    IiSQI=resampleingData(IiSQI,acceptableCount,unacceptableCount,label);
    IbSQI=resampleingData(IbSQI,acceptableCount,unacceptableCount,label);
    IpSQI=resampleingData(IpSQI,acceptableCount,unacceptableCount,label);
    IsSQI=resampleingData(IsSQI,acceptableCount,unacceptableCount,label);
    IkSQI=resampleingData(IkSQI,acceptableCount,unacceptableCount,label);
    IfSQI=resampleingData(IfSQI,acceptableCount,unacceptableCount,label);
    IIiSQI=resampleingData(IIiSQI,acceptableCount,unacceptableCount,label);
    IIbSQI=resampleingData(IIbSQI,acceptableCount,unacceptableCount,label);
    IIpSQI=resampleingData(IIpSQI,acceptableCount,unacceptableCount,label);
    IIsSQI=resampleingData(IIsSQI,acceptableCount,unacceptableCount,label);
    IIkSQI=resampleingData(IIkSQI,acceptableCount,unacceptableCount,label);
    IIfSQI=resampleingData(IIfSQI,acceptableCount,unacceptableCount,label);
    IIIiSQI=resampleingData(IIIiSQI,acceptableCount,unacceptableCount,label);
    IIIbSQI=resampleingData(IIIbSQI,acceptableCount,unacceptableCount,label);
    IIIpSQI=resampleingData(IIIpSQI,acceptableCount,unacceptableCount,label);
    IIIsSQI=resampleingData(IIIsSQI,acceptableCount,unacceptableCount,label);
    IIIkSQI=resampleingData(IIIkSQI,acceptableCount,unacceptableCount,label);
    IIIfSQI=resampleingData(IIIfSQI,acceptableCount,unacceptableCount,label);
    % AVR AVL AVF
    AVRiSQI=resampleingData(AVRiSQI,acceptableCount,unacceptableCount,label);
    AVRbSQI=resampleingData(AVRbSQI,acceptableCount,unacceptableCount,label);
    AVRpSQI=resampleingData(AVRpSQI,acceptableCount,unacceptableCount,label);
    AVRsSQI=resampleingData(AVRsSQI,acceptableCount,unacceptableCount,label);
    AVRkSQI=resampleingData(AVRkSQI,acceptableCount,unacceptableCount,label);
    AVRfSQI=resampleingData(AVRfSQI,acceptableCount,unacceptableCount,label);
    AVLiSQI=resampleingData(AVLiSQI,acceptableCount,unacceptableCount,label);
    AVLbSQI=resampleingData(AVLbSQI,acceptableCount,unacceptableCount,label);
    AVLpSQI=resampleingData(AVLpSQI,acceptableCount,unacceptableCount,label);
    AVLsSQI=resampleingData(AVLsSQI,acceptableCount,unacceptableCount,label);
    AVLkSQI=resampleingData(AVLkSQI,acceptableCount,unacceptableCount,label);
    AVLfSQI=resampleingData(AVLfSQI,acceptableCount,unacceptableCount,label);
    AVFiSQI=resampleingData(AVFiSQI,acceptableCount,unacceptableCount,label);
    AVFbSQI=resampleingData(AVFbSQI,acceptableCount,unacceptableCount,label);
    AVFpSQI=resampleingData(AVFpSQI,acceptableCount,unacceptableCount,label);
    AVFsSQI=resampleingData(AVFsSQI,acceptableCount,unacceptableCount,label);
    AVFkSQI=resampleingData(AVFkSQI,acceptableCount,unacceptableCount,label);
    AVFfSQI=resampleingData(AVFfSQI,acceptableCount,unacceptableCount,label);
    % V1 V2 V3 V4 V5 V6
    V1iSQI=resampleingData(V1iSQI,acceptableCount,unacceptableCount,label);
    V1bSQI=resampleingData(V1bSQI,acceptableCount,unacceptableCount,label);
    V1pSQI=resampleingData(V1pSQI,acceptableCount,unacceptableCount,label);
    V1sSQI=resampleingData(V1sSQI,acceptableCount,unacceptableCount,label);
    V1kSQI=resampleingData(V1kSQI,acceptableCount,unacceptableCount,label);
    V1fSQI=resampleingData(V1fSQI,acceptableCount,unacceptableCount,label);
    V2iSQI=resampleingData(V2iSQI,acceptableCount,unacceptableCount,label);
    V2bSQI=resampleingData(V2bSQI,acceptableCount,unacceptableCount,label);
    V2pSQI=resampleingData(V2pSQI,acceptableCount,unacceptableCount,label);
    V2sSQI=resampleingData(V2sSQI,acceptableCount,unacceptableCount,label);
    V2kSQI=resampleingData(V2kSQI,acceptableCount,unacceptableCount,label);
    V2fSQI=resampleingData(V2fSQI,acceptableCount,unacceptableCount,label);
    V3iSQI=resampleingData(V3iSQI,acceptableCount,unacceptableCount,label);
    V3bSQI=resampleingData(V3bSQI,acceptableCount,unacceptableCount,label);
    V3pSQI=resampleingData(V3pSQI,acceptableCount,unacceptableCount,label);
    V3sSQI=resampleingData(V3sSQI,acceptableCount,unacceptableCount,label);
    V3kSQI=resampleingData(V3kSQI,acceptableCount,unacceptableCount,label);
    V3fSQI=resampleingData(V3fSQI,acceptableCount,unacceptableCount,label);
    V4iSQI=resampleingData(V4iSQI,acceptableCount,unacceptableCount,label);
    V4bSQI=resampleingData(V4bSQI,acceptableCount,unacceptableCount,label);
    V4pSQI=resampleingData(V4pSQI,acceptableCount,unacceptableCount,label);
    V4sSQI=resampleingData(V4sSQI,acceptableCount,unacceptableCount,label);
    V4kSQI=resampleingData(V4kSQI,acceptableCount,unacceptableCount,label);
    V4fSQI=resampleingData(V4fSQI,acceptableCount,unacceptableCount,label);
    V5iSQI=resampleingData(V5iSQI,acceptableCount,unacceptableCount,label);
    V5bSQI=resampleingData(V5bSQI,acceptableCount,unacceptableCount,label);
    V5pSQI=resampleingData(V5pSQI,acceptableCount,unacceptableCount,label);
    V5sSQI=resampleingData(V5sSQI,acceptableCount,unacceptableCount,label);
    V5kSQI=resampleingData(V5kSQI,acceptableCount,unacceptableCount,label);
    V5fSQI=resampleingData(V5fSQI,acceptableCount,unacceptableCount,label);
    V6iSQI=resampleingData(V6iSQI,acceptableCount,unacceptableCount,label);
    V6bSQI=resampleingData(V6bSQI,acceptableCount,unacceptableCount,label);
    V6pSQI=resampleingData(V6pSQI,acceptableCount,unacceptableCount,label);
    V6sSQI=resampleingData(V6sSQI,acceptableCount,unacceptableCount,label);
    V6kSQI=resampleingData(V6kSQI,acceptableCount,unacceptableCount,label);
    V6fSQI=resampleingData(V6fSQI,acceptableCount,unacceptableCount,label);
    %% get new label
    Alabel=label(label==1);
    Ulabel=Alabel.*(-1);
    label=vertcat(Alabel,Ulabel);
    