function [RR1,DET1,LMAX1,ENT1,LAM1,TT1,RR2,DET2,LMAX2,ENT2,LAM2,TT2,RR3,DET3,LMAX3,ENT3,LAM3,TT3,RR4,DET4,LMAX4,ENT4,LAM4,TT4,IiSQI,IbSQI,IpSQI,IsSQI,IkSQI,IfSQI,IIiSQI,IIbSQI,IIpSQI,IIsSQI,IIkSQI,IIfSQI,IIIiSQI,IIIbSQI,IIIpSQI,IIIsSQI,IIIkSQI,IIIfSQI,AVRiSQI,AVRbSQI,AVRpSQI,AVRsSQI,AVRkSQI,AVRfSQI,AVLiSQI,AVLbSQI,AVLpSQI,AVLsSQI,AVLkSQI,AVLfSQI,AVFiSQI,AVFbSQI,AVFpSQI,AVFsSQI,AVFkSQI,AVFfSQI,V1iSQI,V1bSQI,V1pSQI,V1sSQI,V1kSQI,V1fSQI,V2iSQI,V2bSQI,V2pSQI,V2sSQI,V2kSQI,V2fSQI,V3iSQI,V3bSQI,V3pSQI,V3sSQI,V3kSQI,V3fSQI,V4iSQI,V4bSQI,V4pSQI,V4sSQI,V4kSQI,V4fSQI,V5iSQI,V5bSQI,V5pSQI,V5sSQI,V5kSQI,V5fSQI,V6iSQI,V6bSQI,V6pSQI,V6sSQI,V6kSQI,V6fSQI,label] = importfile(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Hongzu\Documents\internship2016\CombineAlgorithm\tempData\setA.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/18 22:23:17

%% Initialize variables.
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
%   column75: double (%f)
%	column76: double (%f)
%   column77: double (%f)
%	column78: double (%f)
%   column79: double (%f)
%	column80: double (%f)
%   column81: double (%f)
%	column82: double (%f)
%   column83: double (%f)
%	column84: double (%f)
%   column85: double (%f)
%	column86: double (%f)
%   column87: double (%f)
%	column88: double (%f)
%   column89: double (%f)
%	column90: double (%f)
%   column91: double (%f)
%	column92: double (%f)
%   column93: double (%f)
%	column94: double (%f)
%   column95: double (%f)
%	column96: double (%f)
%   column97: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
RR1 = dataArray{:, 1};
DET1 = dataArray{:, 2};
LMAX1 = dataArray{:, 3};
ENT1 = dataArray{:, 4};
LAM1 = dataArray{:, 5};
TT1 = dataArray{:, 6};
RR2 = dataArray{:, 7};
DET2 = dataArray{:, 8};
LMAX2 = dataArray{:, 9};
ENT2 = dataArray{:, 10};
LAM2 = dataArray{:, 11};
TT2 = dataArray{:, 12};
RR3 = dataArray{:, 13};
DET3 = dataArray{:, 14};
LMAX3 = dataArray{:, 15};
ENT3 = dataArray{:, 16};
LAM3 = dataArray{:, 17};
TT3 = dataArray{:, 18};
RR4 = dataArray{:, 19};
DET4 = dataArray{:, 20};
LMAX4 = dataArray{:, 21};
ENT4 = dataArray{:, 22};
LAM4 = dataArray{:, 23};
TT4 = dataArray{:, 24};
IiSQI = dataArray{:, 25};
IbSQI = dataArray{:, 26};
IpSQI = dataArray{:, 27};
IsSQI = dataArray{:, 28};
IkSQI = dataArray{:, 29};
IfSQI = dataArray{:, 30};
IIiSQI = dataArray{:, 31};
IIbSQI = dataArray{:, 32};
IIpSQI = dataArray{:, 33};
IIsSQI = dataArray{:, 34};
IIkSQI = dataArray{:, 35};
IIfSQI = dataArray{:, 36};
IIIiSQI = dataArray{:, 37};
IIIbSQI = dataArray{:, 38};
IIIpSQI = dataArray{:, 39};
IIIsSQI = dataArray{:, 40};
IIIkSQI = dataArray{:, 41};
IIIfSQI = dataArray{:, 42};
AVRiSQI = dataArray{:, 43};
AVRbSQI = dataArray{:, 44};
AVRpSQI = dataArray{:, 45};
AVRsSQI = dataArray{:, 46};
AVRkSQI = dataArray{:, 47};
AVRfSQI = dataArray{:, 48};
AVLiSQI = dataArray{:, 49};
AVLbSQI = dataArray{:, 50};
AVLpSQI = dataArray{:, 51};
AVLsSQI = dataArray{:, 52};
AVLkSQI = dataArray{:, 53};
AVLfSQI = dataArray{:, 54};
AVFiSQI = dataArray{:, 55};
AVFbSQI = dataArray{:, 56};
AVFpSQI = dataArray{:, 57};
AVFsSQI = dataArray{:, 58};
AVFkSQI = dataArray{:, 59};
AVFfSQI = dataArray{:, 60};
V1iSQI = dataArray{:, 61};
V1bSQI = dataArray{:, 62};
V1pSQI = dataArray{:, 63};
V1sSQI = dataArray{:, 64};
V1kSQI = dataArray{:, 65};
V1fSQI = dataArray{:, 66};
V2iSQI = dataArray{:, 67};
V2bSQI = dataArray{:, 68};
V2pSQI = dataArray{:, 69};
V2sSQI = dataArray{:, 70};
V2kSQI = dataArray{:, 71};
V2fSQI = dataArray{:, 72};
V3iSQI = dataArray{:, 73};
V3bSQI = dataArray{:, 74};
V3pSQI = dataArray{:, 75};
V3sSQI = dataArray{:, 76};
V3kSQI = dataArray{:, 77};
V3fSQI = dataArray{:, 78};
V4iSQI = dataArray{:, 79};
V4bSQI = dataArray{:, 80};
V4pSQI = dataArray{:, 81};
V4sSQI = dataArray{:, 82};
V4kSQI = dataArray{:, 83};
V4fSQI = dataArray{:, 84};
V5iSQI = dataArray{:, 85};
V5bSQI = dataArray{:, 86};
V5pSQI = dataArray{:, 87};
V5sSQI = dataArray{:, 88};
V5kSQI = dataArray{:, 89};
V5fSQI = dataArray{:, 90};
V6iSQI = dataArray{:, 91};
V6bSQI = dataArray{:, 92};
V6pSQI = dataArray{:, 93};
V6sSQI = dataArray{:, 94};
V6kSQI = dataArray{:, 95};
V6fSQI = dataArray{:, 96};
label = dataArray{:, 97};
